import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const db=new PGlite();
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222', C='33333333-3333-4333-8333-333333333333', D='44444444-4444-4444-8444-444444444444', P='55555555-5555-4555-8555-555555555555';
const code='a'.repeat(64), hash=createHash('sha256').update(code).digest('hex');
const q=(sql,args=[])=>db.query(sql,args);
const as=async id=>{await q("select set_config('app.user_id',$1,false)",[id]);};
const fails=async(sql,args,pattern)=>assert.rejects(()=>q(sql,args),pattern);
try {
  await db.exec(`create role anon;create role authenticated;create role service_role;
    create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('app.user_id',true),'')::uuid$$;
    create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
    create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;`);
  for(const file of ['001_schema.sql','004_deep_audit_fixes.sql','005_offline_absolute_times.sql','006_terminal_edit_guard.sql','007_reject_and_hide.sql','008_fix_null_pair_guard.sql','009_bug_hunt_2.sql','010_low_priority_fixes.sql','011_backend_capabilities.sql','012_chatgpt_action_integration.sql']) {
    await db.exec((await readFile(`supabase/migrations/${file}`,'utf8')).replace(/create extension if not exists pgcrypto;\s*/i,''));
  }
  await q(`insert into auth.users values ($1,'owner@example.test',now()),($2,'partner@example.test',now()),($3,'new@example.test',now()),($4,'other@example.test',null)`,[A,B,C,D]);
  await q(`insert into profiles(id,display_name,email) values ($1,'Owner','owner@example.test'),($2,'Partner','partner@example.test');`,[A,B]);
  await q(`insert into pairs(id,name) values($1,'Test group')`,[P]);
  await q(`insert into pair_members(pair_id,user_id,role) values($1,$2,'owner'),($1,$3,'member')`,[P,A,B]);
  await as(A);
  await q(`select api_create_task($1,gen_random_uuid(),$2,'Existing task',null,now()+interval '1 hour','Europe/Bratislava',1,0,'none','after',true,60,10)`,['66666666-6666-4666-8666-666666666666',B]);
  const before=(await q(`select pg_get_functiondef('public.api_create_task(uuid,uuid,uuid,text,text,timestamptz,text,integer,integer,text,text,boolean,integer,integer)'::regprocedure) as value`)).rows[0].value;
  await db.exec(await readFile('supabase/migrations/013_group_invitations.sql','utf8'));
  assert.equal((await q('select get_backend_capabilities() as c')).rows[0].c.schema_version,13);
  assert.equal((await q(`select pg_get_functiondef('public.api_create_task(uuid,uuid,uuid,text,text,timestamptz,text,integer,integer,text,text,boolean,integer,integer)'::regprocedure) as value`)).rows[0].value,before);
  assert.equal((await q('select partner_id from pair_primary_partners where actor_id=$1',[A])).rows[0].partner_id,B);
  await fails('select create_group_invitation($1,$2,false)',['new@example.test',hash],/SHARED_TASKS_CONFIRMATION_REQUIRED/);
  await as(B);await fails('select create_group_invitation($1,$2,true)',['new@example.test',hash],/GROUP_OWNER_REQUIRED/);
  await as(A);
  const invite=(await q('select create_group_invitation($1,$2,true) as i',['new@example.test',hash])).rows[0].i;
  assert.ok(!JSON.stringify(invite).includes(hash));
  await fails('select create_group_invitation($1,$2,true)',['new@example.test','b'.repeat(64)],/INVITATION_ALREADY_ACTIVE/);
  await as(D);await fails('select accept_group_invitation($1,$2,true)',[code,'New'],/EMAIL_CONFIRMATION_REQUIRED/);
  await q('update auth.users set email_confirmed_at=now() where id=$1',[D]);
  await fails('select accept_group_invitation($1,$2,true)',[code,'New'],/INVITATION_INVALID_OR_EXPIRED/);
  await as(C);
  await fails('select accept_group_invitation($1,$2,false)',[code,'New'],/SHARED_TASKS_CONFIRMATION_REQUIRED/);
  await fails('select accept_group_invitation($1,$2,true)',['0'.repeat(64),'New'],/INVITATION_INVALID_OR_EXPIRED/);
  await q('update group_invitations set expires_at=now()-interval \'1 second\' where id=$1',[invite.id]);
  await fails('select accept_group_invitation($1,$2,true)',[code,'New'],/INVITATION_INVALID_OR_EXPIRED/);
  await q('update group_invitations set expires_at=now()+interval \'1 day\' where id=$1',[invite.id]);
  assert.equal((await q('select accept_group_invitation($1,$2,true) as p',[code,'New'])).rows[0].p,P);
  assert.equal((await q('select accept_group_invitation($1,$2,true) as p',[code,'New'])).rows[0].p,P);
  assert.equal((await q('select count(*)::int as n from pair_members where pair_id=$1',[P])).rows[0].n,3);
  assert.equal((await q('select partner_id from pair_primary_partners where actor_id=$1',[A])).rows[0].partner_id,B);
  assert.equal((await q('select partner_id from pair_primary_partners where actor_id=$1',[C])).rows[0].partner_id,A);
  await db.exec('grant usage on schema public,auth to authenticated;grant select on tasks,profiles,pairs,pair_members to authenticated;set role authenticated;');
  assert.equal((await q('select count(*)::int as n from tasks')).rows[0].n,1,'New member can see the existing group task via RLS');
  await fails('select * from group_invitations',[],/permission denied/);
  await fails('select list_group_invitations()',[],/GROUP_OWNER_REQUIRED/);
  await as(D);assert.equal((await q('select count(*)::int as n from tasks')).rows[0].n,0,'Outsider cannot see tasks');
  await db.exec('reset role');await as(A);
  const task='77777777-7777-4777-8777-777777777777';
  await q(`select api_create_task($1,gen_random_uuid(),$2,'For third member',null,now()+interval '1 hour','Europe/Bratislava',1,0,'none','after',true,60,10)`,[task,C]);
  assert.equal((await q(`select count(*)::int as n from notification_jobs where task_id=$1 and recipient_id=$2 and kind='task_assigned'`,[task,C])).rows[0].n,1);
  await as(C);await q('select api_complete_task($1,gen_random_uuid())',[task]);
  await q('select api_complete_task($1,gen_random_uuid())',[task]);
  assert.equal((await q(`select count(*)::int as n from notification_jobs where task_id=$1 and recipient_id=$2 and kind='task_completed'`,[task,A])).rows[0].n,1);
  await as(A);
  const code2='c'.repeat(64),hash2=createHash('sha256').update(code2).digest('hex');
  const revoked=(await q('select create_group_invitation($1,$2,true) as i',['other@example.test',hash2])).rows[0].i;
  await q('select revoke_group_invitation($1)',[revoked.id]);await as(D);
  await fails('select accept_group_invitation($1,$2,true)',[code2,'Other'],/INVITATION_INVALID_OR_EXPIRED/);
  assert.equal((await q(`select has_function_privilege('anon','public.accept_group_invitation(text,text,boolean)','EXECUTE') as allowed`)).rows[0].allowed,false);
  assert.equal((await q('select count(*)::int as n from tasks')).rows[0].n,2,'Existing tasks retained');
  console.log('GROUP SQL: invitation permissions, email binding, expiry, replay, revocation, shared visibility and completion notifications OK');
}finally{await db.close();}
